version: "3.1"

services: 
    db:
        image: mysql:5.7
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=bootcamp2021
        restart: always
    
    phpmyadmin:
        image: phpmyadmin
        ports: 
            - 8080:80
        links: 
            - db
        restart: always