version: "3.1"
services:
    db:
        image: mysql:5.7
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=bootcamp2021
    mushteri:
        image: phpmyadmin
        ports: 
            - 8081:80
        links:  
            - db:db
        